name: Destroy Infrastructure

on:
  push:
    branches: [ "main" ]

jobs:
  destroy-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Empty S3 Bucket
        run: |
          aws s3 rm s3://prepsphere-frontend-production --recursive || true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init & Destroy
        run: |
          cd terraform
          terraform init
          terraform destroy -auto-approve
        env:
          TF_VAR_mongodb_url: ${{ secrets.MONGODB_URL }}
          TF_VAR_postgres_url: ${{ secrets.POSTGRES_URL }}
          TF_VAR_groq_api_key: ${{ secrets.GROQ_API_KEY }}
          TF_VAR_razorpay_key_id: ${{ secrets.RAZORPAY_KEY_ID }}
          TF_VAR_razorpay_key_secret: ${{ secrets.RAZORPAY_KEY_SECRET }}
          TF_VAR_razorpay_webhook_secret: ${{ secrets.RAZORPAY_WEBHOOK_SECRET }}
